#include "xps_mime.h"

//here, some extension-mime types pairs are given, you can add as required
xps_keyval_t mime_types[] = {
    {".c", "text/x-c"},
    {".cc", "text/x-c"},
    {".cpp", "text/x-c"},
    {".dir", "application/x-director"},
    {".dxr", "application/x-director"},
    {".fgd", "application/x-director"},
    {".swa", "application/x-director"},
    {".text", "text/plain"},
    {".txt", "text/plain"},
    {".png", "image/png"},
    {".png", "image/x-png"},
    {".jpg", "image/jpeg"},
    {".jpeg", "image/jpeg"},
    {".gif", "image/gif"},
    {".bmp", "image/bmp"},
    {".webp", "image/webp"},
    {".svg", "image/svg+xml"},
    {".ico", "image/x-icon"},
    {".mp3", "audio/mpeg"},
    {".wav", "audio/wav"},
    {".mp4", "video/mp4"},
    {".avi", "video/x-msvideo"},
    {".html", "text/html"},
    {".htm", "text/html"},
    {".css", "text/css"},
    {".js", "application/javascript"},
    {".json", "application/json"},
    {".xml", "application/xml"},
    {".pdf", "application/pdf"},
    {".doc", "application/msword"},
    {".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
    {".xls", "application/vnd.ms-excel"},
    {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
    {".ppt", "application/vnd.ms-powerpoint"},
    {".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
    {".zip", "application/zip"},
    {".rar", "application/x-rar-compressed"},
    {".7z", "application/x-7z-compressed"},
    {".tar", "application/x-tar"},
    {".gz", "application/gzip"},
    {".bz2", "application/x-bzip2"},
    {".xz", "application/x-xz"},
    {".exe", "application/x-msdownload"},
    {".dll", "application/x-msdownload"},
    {".msi", "application/x-msdownload"},
    {".apk", "application/vnd.android.package-archive"},
    {".dmg", "application/x-apple-diskimage"},
    {".iso", "application/x-iso9660-image"},
    {".deb", "application/x-debian-package"},
    {".rpm", "application/x-redhat-package-manager"},
    {".sh", "application/x-sh"},
    {".bat", "application/x-msdownload"},
    {".ps1", "application/x-powershell"},
    {".py", "text/x-python"},
    {".php", "text/x-php"},
    {".rb", "text/x-ruby"},
    {".go", "text/x-go"},
    {".rs", "text/x-rust"},
    {".swift", "text/x-swift"},
    {".kt", "text/x-kotlin"},
    {".dart", "text/x-dart"},
    {".lua", "text/x-lua"},
    {".pl", "text/x-perl"},
    {".pm", "text/x-perl"},
    {".r", "text/x-r"},
    {".m", "text/x-matlab"},
    {".ipynb", "application/x-ipynb+json"},
    {".wasm", "application/wasm"},
    {".ttf", "font/ttf"},
    {".woff", "font/woff"},
    {".woff2", "font/woff2"},
    {".eot", "application/vnd.ms-fontobject"},
    {".otf", "font/otf"},
    {".mp4", "video/mp4"},
    {".mov", "video/quicktime"},
    {".webm", "video/webm"},
    {".flv", "video/x-flv"},
    {".mkv", "video/x-matroska"},
    {".3gp", "video/3gpp"},
    {".3g2", "video/3gpp2"},
    {".aac", "audio/aac"},
    {".ogg", "audio/ogg"},
    {".flac", "audio/flac"},
    {".mid", "audio/midi"},
    {".midi", "audio/midi"},
    {".amr", "audio/amr"},
    {".au", "audio/basic"},
    {".aiff", "audio/x-aiff"},
    {".aif", "audio/x-aiff"},
    {".aifc", "audio/x-aiff"},
    {".m4a", "audio/mp4"},
    {".m4b", "audio/mp4"},
    {".m4p", "audio/mp4"},
    {".m4r", "audio/mp4"},
    {".m4v", "video/mp4"},
    {".mp2", "audio/mpeg"},
    {".mp2a", "audio/mpeg"},
    {".mp3", "audio/mpeg"},
    {".mpa", "audio/mpeg"},
    {".mpga", "audio/mpeg"},
    {".oga", "audio/ogg"},
    {".ogv", "video/ogg"},
    {".opus", "audio/opus"},
    {".spx", "audio/ogg"},
    {".wav", "audio/wav"},
    {".wave", "audio/wav"},
    {".webp", "image/webp"},
    {".apng", "image/apng"},
    {".avif", "image/avif"},
    {".bmp", "image/bmp"},
    {".gif", "image/gif"},
    {".ief", "image/ief"},
    {".jpeg", "image/jpeg"},
    {".jpg", "image/jpeg"},
    {".jfif", "image/jpeg"},
    {".pbm", "image/x-portable-bitmap"},
    {".pgm", "image/x-portable-graymap"},
    {".png", "image/png"},
    {".pnm", "image/x-portable-anymap"},
    {".ppm", "image/x-portable-pixmap"},
    {".ras", "image/x-cmu-raster"},
    {".rgb", "image/x-rgb"},
    {".svg", "image/svg+xml"},
    {".tif", "image/tiff"},
    {".tiff", "image/tiff"},
    {".xbm", "image/x-xbitmap"},
    {".xpm", "image/x-xpixmap"},
    {".xwd", "image/x-xwindowdump"},
    {".css", "text/css"},
    {".html", "text/html"},
    {".htm", "text/html"},
    {".shtml", "text/html"},
    {".js", "application/javascript"},
    {".mjs", "application/javascript"},
    {".cjs", "application/javascript"},
    {".json", "application/json"},
    {".xml", "application/xml"},
    {".rss", "application/rss+xml"},
    {".atom", "application/atom+xml"},
    {".pdf", "application/pdf"},
    {".doc", "application/msword"},
    {".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"},
    {".xls", "application/vnd.ms-excel"},
    {".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
    {".ppt", "application/vnd.ms-powerpoint"},
    {".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"},
    {".odp", "application/vnd.oasis.opendocument"}
};
int n_mimes = sizeof(mime_types) / sizeof(mime_types[0]);

const char *xps_get_mime(const char *file_path) {
    const char *ext = get_file_ext(file_path);

    if (ext == NULL)
        return NULL;

    for (int i = 0; i < n_mimes; i++) {
    if (strcmp(mime_types[i].key, ext) == 0)
        return mime_types[i].val;
    }

    return NULL;
}